name: 🚀 Deploy to Hostinger

on:
  push:
    branches:
      - main   # Déploie quand tu push sur main (change si besoin)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # vérifie ta version Node

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: /dist/khroonos.com   # chemin du build NX
          server-dir: /public_html         # destination sur Hostinger