name: Deploy to Hostinger (SFTP Alternative)

on:
  workflow_dispatch: # Manuel uniquement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean cache
        run: npm run clean

      - name: Build project
        run: npm run build

      - name: List build output
        run: ls -la out/

      - name: Deploy to Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './out/*'
          remote_path: '/public_html/'
          sftp_only: true

