name: Deploy to Hostinger

on:
  push:
    branches: [main]
  workflow_dispatch: # Permet de lancer le déploiement manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean cache
        run: npm run clean

      - name: Build project
        run: npm run build

      - name: List build output
        run: ls -la out/

      - name: Check for index.html
        run: |
          echo "=== Vérification de la structure du build ==="
          if [ -f "out/index.html" ]; then
            echo "✅ index.html trouvé à la racine de out/"
          else
            echo "❌ index.html non trouvé à la racine de out/"
            exit 1
          fi
          echo "=== Fichiers HTML générés ==="
          find out/ -name "*.html" | head -20

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./out/
          server-dir: /domains/khroonos.com/public_html/
          dangerous-clean-slate: true
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

